### PR TITLE
changing OdometryInterval to 50 to avoid overshooting

### PR DESCRIPTION
**Pull request by bfalacerda**

### CODE REVIEW

**Comment by cdondrup** [comment]
This might influence the performance of the `mdl_people_tracker`. Since this is not the standard currently used, it shouldn't be a problem. Just wanted to mention it.

**Comment by bfalacerda** [comment]
what do you mean by " Since this is not the standard currently used, it shouldn't be a problem"?

**Comment by cdondrup** [comment]
Atm the `bayes_people_tracker` is used. The `mdl_people_tracker` (the Aachen one) is still there and the data is recorded but it is not the one used in nodes using the positions of people.

**Comment by bfalacerda** [comment]
ok, maybe open an issue there then, so we dont forget to test with the slower odometry later on. With the new firmware, keeping the rate at 20 is awful. He overshoots like crazy

**Comment by nilsbore** [comment]
We should try something like 30 as well, it seems to work reasonably here.

**Comment by bfalacerda** [comment]
yeah, that 50 has zero thougth behind it except "its larger than 20 and it works"

**Pull request merged**
