### PR TITLE
Update indigo branch to use latest MIRA version.

### PR DESCRIPTION
**Pull request by cburbridge**

### CODE REVIEW

**Comment by marc-hanheide** [comment]
no surprise... this now fails for hydro :-(

**Comment by marc-hanheide** [comment]
also... in the current settings all pull requests are only checked for hydro...

**Comment by cburbridge** [comment]
ok, but if i merge this it wont break the hydro version even though jenkins is upset?

**Comment by marc-hanheide** [comment]
no... this is just the PR checking being a little messy... It checks all PR's against hydro... It should _filter_ only PRs that are for the respective branch, but it currently doesn't. Feel free to ignore.

**Comment by marc-hanheide** [comment]
Oh... just spotted this one:

```
/tmp/test_repositories/src_repository/scitos_drivers/scitos_mira/src/ScitosModule.cpp:23:1140: warning: too many arguments for format [-Wformat-extra-args]
    ROS_WARN("Mira RPC error caught when setting parameter: ", e.what() );
```

**Comment by cburbridge** [comment]
Yes, will update this in a separate PR.

**Pull request merged**
