### PR TITLE
fixing circular dependencies

### PR DESCRIPTION
**Pull request by Jailander**

### CODE REVIEW

**Comment by cdondrup** [comment]
Not really a relevant comment to this PR but I think that most of the run_depends in scitos_bringup are unnecessary. Why strands_ui, strands_navigation, or scitos_2d_navigation?

**Comment by Jailander** [comment]
hmm true I'll fix it

**Comment by marc-hanheide** [comment]
@Jailander will you fix it in this PR, then I'll wait merging it.

**Comment by Jailander** [comment]
yes sorry give me a minute ;)

**Pull request merged**
