### PR TITLE
Don't reset odometry on start.

### PR DESCRIPTION
**Pull request by cburbridge**
Allows restarting the mira interface node without messing up amcl.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
Will this have any side effects? E.g. a numerical overrun?

**Comment by marc-hanheide** [comment]
Hopefully fixes https://github.com/strands-project/scitos_robot/issues/10

**Comment by cburbridge** [comment]
I really doubt it but we will have to see.

**Comment by marc-hanheide** [comment]
OK, I think this is important to merge and re-release. I'll do that.

**Pull request merged**
