### PR TITLE
Adding respawn to scitos node, removing launch files from scitos drivers...

### PR DESCRIPTION
**Pull request by Jailander**
..., making scitos drivers a metapackage again this also solves #80

### CODE REVIEW

**Comment by Jailander** [comment]
@marc-hanheide I don't understand why this failed now i am getting this error, do you know what is wrong?

`stderr: fatal: unable to access 'https://github.com/strands-project/scitos_drivers.git/': gnutls_handshake() failed: A TLS packet with unexpected length was received.`

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
That's one of the annoying network issues I can't do anything about. The last comment is understood by Jenkins to test again. You can also use it next time you see it failing with some network error

**Comment by Jailander** [comment]
cool! thank you @marc-hanheide

**Comment by cdondrup** [comment]
This time it worked

**Pull request merged**
